### ISSUE TITLE
NIF compile warnings every time `mix compile` runs

### ISSUE THREAD

**Issue by axelson** [memoetapp/memoet#34]
Whenever I run `mix compile` I get the following warnings:
```
jason@jdesktop ~/d/f/memoet (general-improvements)> mix compile
no .env file found!
Compiling NIF crate :sm2 (native/sm2)...
warning: method is never used: `set_new_position`
  --> src/srs/card.rs:78:5
   |
78 |     pub fn set_new_position(&mut self, position: i64) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: function is never used: `time_span`
  --> src/svc/timespan.rs:19:8
   |
19 | pub fn time_span(seconds: f32, precise: bool) -> String {
   |        ^^^^^^^^^

warning: method is never used: `new`
  --> src/svc/timestamp.rs:13:5
   |
13 |     pub fn new() -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
```
I understand why the `.env` warning is there (since it is loaded in the config files), but I'm not sure why the rust warnings are shown every time, instead of just once the first time that everything is compiled.

**Comment by manhtai** [comment]
I think this is how Rustler work. If we don't want to invoke Rust compiler every time, we need to configure `load_from` and set `skip_compilation?` option to `true`.

Anyway, I have no problem with this, better get off all the warnings instead though.

**Comment by axelson** [comment]
I think the main thing in my mind here is to fix the warnings, it seems like those functions can all be safely removed.

**Comment by manhtai** [comment]
Yeah, except the `new()` function which is used for some tests.

Anyway, I've removed/annotated all unused functions, it should be clear of warnings now.

**Comment by axelson** [comment]
That fix works. Thanks :+1:
