### ISSUE TITLE
Bug: No Database Connection Possible nxdomain for localhost

### ISSUE THREAD

**Issue by Daniel-CS-Team** [memoetapp/memoet#55]
I built the Dockerimage using the provided Dockerfile in this Repo. When Using the docker-compose.yml I get the following Error:

`[error] Postgrex.Protocol (#PID<0.2660.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (127.0.0.1:5432): non-existing domain - :nxdomain`

Note the nxdomain for 127.0.0.1. I trie different settings, using localhost, AWS Aurora Endpoint or IP directly. All with the same result. Thie means, that the project is currently unusable.

**Comment by manhtai** [comment]
If it's the same error maybe you're setting the wrong value for `DATABASE_URL`. Can you double check it? I deployed it to fly.io using the same Dockerfile and it's still running on memoet.fly.dev as of now.

**Comment by Daniel-CS-Team** [comment]
Thanks for the quick Response.
This is the value for DATABASE_URL:
postgres://postgres:6F4548EA-F675-4074-9BBF-E69731BA8C82@127.0.0.1/postgres

Password has been genereated with uuidgen (will change it anyways).

**Comment by manhtai** [comment]
Oh you're using 127.0.0.1, from docker container view point, it sure can't find the IP, to use with postgres container on docker-compose, set 127.0.0.1 to `postgres` as in original [file](https://github.com/memoetapp/memoet/blob/master/docker-compose.yml).

**Comment by Daniel-CS-Team** [comment]
Well, the container is running in AWS FARGATE where there is no container network but all is mapped to localhost. Anyways, I can reproduce the problem when running in my local dockerd using your original docker-compose.yml

**Comment by manhtai** [comment]
I've just tried on my local, turn out it's because ipv6 default support for db, fixed that by turning default off, please use the latest code from master branch.

**Comment by Daniel-CS-Team** [comment]
Thank you very much. It works now.
