### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by geblanco** [memoetapp/memoet#58]
Hi there!

First of all, thanks for this great app! It looks awesome!

I am trying to build the application locally using Docker, but I think versions are not correctly pinned. Your ubuntu deploy script installs `nodejs-16`, but elixir alpine Docker image installs `nodejs-19` when `apk add npm` (and I am not able to find previous versions of npm). This in turn causes node-sass (which, btw is deprecated) to miserably refuse to compile...

I've solved it by setting `"node-sass": "^8.0.0"` in the package.json. It successfully builds the image though I had no time to check if everything is working.

I see two possible pathways, either pin npm version to nodejs-16 (I don't know if using `apk add` or `asdf` inside the Docker image) or update package.json and .lock to allow for these changes. I could submit a PR for the latter.

What do you think?
Best,

**Comment by manhtai** [comment]
Thanks for your concerns, please submit a PR as you see fit, as long as the CI passed I think we're fine. Will take a look on this issue in this weekend if you don't though.

**Comment by manhtai** [comment]
Fixed in #59 @geblanco!

**Comment by geblanco** [comment]
Awesome @manhtai! Way better solution than what I was thinking on submitting :)

Thank you!
